name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python {{cookiecutter.python_version}}
        uses: actions/setup-python@v1
        with:
          python-version: {{cookiecutter.python_version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python setup.py install
      - name: Lint with TBD
        run:
          echo "TODO linting here"